### ISSUE TITLE
Discarding relations does not work like described in README

### ISSUE THREAD

**Issue by bjorne** [jhawthorn/discard#10]
I'm trying to implement the `after_discard` callback to discard related objects.

The README says that a post's comments can be discarded like so;

```ruby
has_many :comments
after_discard do
  comments.discard_all
end
```

However, this is what I'm seeing

```ruby
> Post.last.discard
NoMethodError: undefined method `discard_all' for #<ActiveRecord::Associations::CollectionProxy []>
```

I'm guessing that the `discard_all` class method added by this library is not understood by `CollectionProxy`. I'm running ActiveRecord 5.1.4, has anything changed recently?

The immediate workaround I'm seeing is doing `comments.each(&:discard)` which is perhaps not as elegant but does the job. Any better ideas?

**Comment by mattrw89** [comment]
Thanks for posting this @bjorne. I just hit this issue also. 

`#<NoMethodError: undefined method `discard_all' for #<Attachment::ActiveRecord_Associations_CollectionProxy:0x007fb462b39d18>>`

In model.rb you are defining discard_all/undiscard_all methods:

`module ClassMethods
      def discard_all
        all.each(&:discard)
      end
      def undiscard_all
        all.each(&:undiscard)
      end
    end`

I imagine that this would need to be added to CollectionProxy somehow to get the expected outcome. Also, the code is doing basically exactly what you proposed as the workaround @bjorne.

**Comment by mattrw89** [comment]
Update... I just realized that I forgot to add `include Discard::Model` to the relations, which would explain why those relations don't have methods! All seems to work well for me now.

**Comment by jhawthorn** [comment]
@bjorne I'm assuming you're in the same boat as @mattrw89, and closing this issue. I've added a spec in abf3715e1052703a48948a747a681add0adc13b4 to ensure this works. If it doesn't please file a new issue :heart:.

It seems like forgetting to include `Discard::Model` will be a common enough mistake, which makes sense, nothing explicitly states this.

I've added a little hint in the README a169f0f5272651e071ff17ee404e3742afc3ed9 which should hopefully clarify this.

Thank you both.
