### ISSUE TITLE
Warden/Devise: Preventing login for discarded users?

### ISSUE THREAD

**Issue by rlue** [jhawthorn/discard#11]
Has anyone else worked on how to prevent discarded users from logging in? I'm on a Rails app with Devise, so of course a naive solution would be to override the default controller behavior — but since I imagine this is not an uncommon scenario, I'm curious to know if anyone's worked out a more portable solution.

`Devise::SessionsController#create` calls `warden.authenticate!` ([source](https://github.com/hassox/warden/blob/master/lib/warden/proxy.rb#L132-L136)) before anything else, so I thought that might be a good place to start.

What would be the best way to extend Warden's behavior in this case?

**Comment by jhawthorn** [comment]
#9 has added instructions for devise :tada:

(If this doesn't address your issue, please file another :heart: )
