### ISSUE TITLE
Adding an config parameter to skip update/save hooks/validations

### ISSUE THREAD

**Issue by vishthemenon** [jhawthorn/discard#18]
Picking up the issue brought up by @artemf from #4.

Although for most applications, running update hooks with the discard method should not have any catastrophic, unexpected side-effect, I think it is better to have the ability to choose here. Especially since it is not intuitive to expect 'update' hooks to be run for a method that more similar to 'destroy'. One possible solution is to use `update_attribute` instead of `save` but there may be more elegant methods.

**Comment by jhawthorn** [comment]
Thanks for the writeup, but I don't want this. Sorry.

> it is not intuitive to expect 'update' hooks to be run for a method that more similar to 'destroy'.

A discard _is_ an update. One of the goals of discard is to make this more obvious.
