### ISSUE TITLE
Documentation for un/discard is not completely correct

### ISSUE THREAD

**Issue by aried3r** [jhawthorn/discard#20]
https://github.com/jhawthorn/discard/blob/cb3c885849ce494b426a1e99d2049eaba8145f16/lib/discard/model.rb#L71-L75

I think either these should return `false` if it's already discarded or the documentation should read "true if successful or a falsey value". Since the guard clause will make it return `nil`.

I can submit a PR if you want. Just let me know which option you like better. :)

**Comment by Onumis** [comment]
just `return true if discarded?` imo, or:

```
    def discard
      discarded? || 
        run_callbacks(:discard) do
          update_attribute(self.class.discard_column, Time.current)
        end
    end
```

**Comment by aried3r** [comment]
I kinda like the guard clause better, even though I also like having only a single return statement. But `bool OR &block` over 4 lines looks a bit weird to me.

I'll submit a PR soon!
