### ISSUE TITLE
Discarding on nested attributes doesn't trigger callbacks

### ISSUE THREAD

**Issue by aried3r** [jhawthorn/discard#21]
Hey!

I read https://github.com/jhawthorn/discard/issues/7#issuecomment-369797910 which is the solution to this particular issue. But one thing that isn't mentioned is that this will not trigger `after_discarded` callbacks, if any.

I think paper_trail solved this by checking on `after_update` if any of the tracked attributes were changed, and if so, create a version, run callbacks etc.

Maybe this is a route this gem could also take?

**Comment by jarednorman** [comment]
Because this issue is more than a year old, I'm going to close it. It sounds like there might be a real issue worth investigating, though. If you could provide a spec that demonstrates the issue, I'm happy to look into it.
