### ISSUE TITLE
Add section on README about integration with counter_culture gem

### ISSUE THREAD

**Issue by rainerborene** [jhawthorn/discard#22]
[`counter_culture`](https://github.com/magnusvk/counter_culture/) automatically sets callbacks for `paranoia` events which are quite similar to `discard`. See [this piece](https://github.com/magnusvk/counter_culture/blob/3070845a4af6a3076c66f488f3af7d7feba0c762/lib/counter_culture/extensions.rb#L22-L33) of code for reference. And here's what I'm currently doing:

```ruby
class ApplicationRecord < ActiveRecord::Base
  include Discard::Model
  self.discard_column = :deleted_at

  def self.discardable
    default_scope -> { kept }
    if self.after_commit_counter_cache.present?
      after_discard :_update_counts_after_destroy
      after_undiscard :_update_counts_after_create
    end
  end
end
```

I think it's worth adding this to the README file.

**Comment by skatkov** [comment]
Suggesting usage of default_scope doesn't sound like a good advice for a readme.

**Comment by jhawthorn** [comment]
Thanks. I'm sure this is helpful information for users, but I want to discourage use of `default_scope` as much as possible. I worry having more of the README dedicated to it will have more users use it.

Maybe this would fit well in the wiki and the README could link to it?

**Comment by reidab** [comment]
Rather than go down the default_scope path, I tossed together a PR to add Discard support to counter_culture: https://github.com/magnusvk/counter_culture/pull/220

If that gets merged, this issue may be moot.

**Comment by rainerborene** [comment]
now that this feature was merged on `counter_culture` we can close this issue. thanks @reidab
