### ISSUE TITLE
Mongoid support

### ISSUE THREAD

**Issue by stanley90** [jhawthorn/discard#23]
I'm trying to use this gem with https://github.com/mongodb/mongoid and a few small changes are needed:

* changing the `activerecord` dependency to `activesupport` (there doesn't seem to be any ActiveRecord dependency anyway)
* add Mongoid field `field discard_column, type: Time` in the `included` block of `Discard::Model` - needs to be done in a way that it doesn't break the ActiveRecord version
* adjust the scopes to work with Mongoid

Possibly should be done as a separate gem in addition to `discard`?

**Comment by jhawthorn** [comment]
Thanks for the issue!

> Possibly should be done as a separate gem in addition to discard?

I'd prefer this.

I'd like to keep discard really small, and not have it grow much bigger than it is now. (It really doesn't do much, it's more a set of conventions than a real tool).

I'm open to making changes which make a mongoid integration easier so long as they don't add much complexity. (If much complexity is required, it would probably be best for users of both AR and mongoid to just have a totally separate fork)

> adjust the scopes to work with Mongoid

I'd be okay with moving `Discard::Model::ClassMethods` into a different class like `Discard::Scopes`. With this we could add something like `extend Discard::Scopes if self < ActiveRecord::Base` to the `included` block (perhaps something more explicit, but I do want to follow SemVer strictly and not change that API)

> changing the `activerecord` dependency to `activesupport`

Changing it to `activemodel` would be :ok_hand: by me, so long as we also make the change to the scopes I describe above (the scopes do make ActiveRecord required).

> add Mongoid field `field discard_column, type: Time` in the included block of Discard::Model - needs to be done in a way that it doesn't break the ActiveRecord version

I'm not familiar with Mongoid or libraries for it, but I feel like it would be best to just explicitly declare the field. If this is desired, as long as it is in the Mongoid-specific gem, that's :+1:

**Comment by hobbypunk90** [comment]
i know this issue is closed for a while, but today i ran in this problem 😁 (i had discard in gem list and it loads active record and i searched a while why activerecord is laoded - it maked me crazy 😁)
i forked and changed the gem. The changes are about 6 lines, only one scope didn't work with mongoid.

if it's ok for @jhawthorn i would like to create a merge request for the changes.
