### ISSUE TITLE
Bang in the methods discard and undiscard

### ISSUE THREAD

**Issue by celsoMartins** [jhawthorn/discard#27]
Hey. Congratulations for the great job. I've started to use it today and seems to be a useful tool.

But the methods "discard" and "undiscard", following the rails patterns, should not have a bang, since it changes the database?

discard!
undiscard!

**Comment by jhawthorn** [comment]
Methods don't need to have a bang to change the database (`model.save` exists), but they do to raise an error on failing (like `model.save!`).

We've just added `discard!` and `undiscard!` in #17 :tada:, but there hasn't been a release yet with that change.

Hope that helps!

**Comment by lucabob** [comment]
@jhawthorn Any chance you could do a release, so that these methods are included?
