### ISSUE TITLE
Need new version of gem

### ISSUE THREAD

**Issue by jonkarna** [jhawthorn/discard#36]
Notable: master doesn't run validations

https://github.com/jhawthorn/discard/compare/v1.0.0...master

**Comment by rsmithlal** [comment]
Can you clarify what you mean? Do you mean that models using this gem do not run their own validations when the module is included in the class?

**Comment by jonkarna** [comment]
Good:
Master doesn't run validations when executing discard

Bad:
Current gem version is behind master and runs validations when executing discard. (e.g. thing.discard # => false because this record isn't valid)

**Comment by rsmithlal** [comment]
Ah I see, thanks! Considering using the gem for my project so this is useful info.

**Comment by jonkarna** [comment]
I would suggest working off of master. Another thing to look out for is that this doesn't come with all the bells and whistles other gems do (not a bad thing), so be on a lookout for those possibilities.

**Comment by yasyf** [comment]
Any chance we can get a gem release soon? Thanks!
