### ISSUE TITLE
Uniqueness validation triggered for records that have been discarded 

### ISSUE THREAD

**Issue by JamesDullaghan** [jhawthorn/discard#37]
After a record has been discarded with a uniqueness validation, it seems the uniqueness validation is not ignored for subsequent records.

Is there any way around this?

**Comment by rsmithlal** [comment]
It's possible that you would have to rework your uniqueness validator to capture information about the `discarded_at` column. I know that when defining one, you can pass a `scope` option, so that might be helpful. 

The only issue might be that the value for the `discarded_at` column will almost always be a unique datetime, so you might have to add a boolean `discarded` column to your tables to use as your validator scope and set it using a `before_discard` callback. That way, your validator will check for a unique combination of each the column being validated and whether or not it has been discarded. This might not be ideal, but I suspect that it would work.

**Comment by tmock12** [comment]
For the reasons @rsmithlal mentioned, using `scope` is probably a bad idea. Thankfully `validates_uniqueness_of` comes [with a conditions option](https://apidock.com/rails/ActiveRecord/Validations/ClassMethods/validates_uniqueness_of). Using that I **think** you can achieve what you want with something like:

```ruby
validates_uniqueness_of :email, conditions: -> { where(discarded_at: nil) }
# or:
validates :email, uniquess: { conditions: -> { where(discarded_at: nil) } }
```

This should only check uniqueness of emails on non 'deleted' (AKA discarded) records.

**Comment by pboling** [comment]
@JamesDullaghan You can add an index to support the validation if you are using a nice database (PostgreSQL, MySQL...).

It would prevent undiscarding records though if there has been a conflicting record created, as @rsmithlal mentioned.

To insulate yourself from the potential craziness, you may want to have two unique indexes, ensuring you only ever have one discarded and one not discarded.  It will depend on how you intend to use the data.

```
class AddUniquenessConstraint < ActiveRecord::Migration[5.2]
  def change
    add_index :users, %i[email], where: '(discarded_at IS NOT NULL)', name: 'idx_users_email_discarded_at_not_null'
    add_index :users, %i[email], where: '(discarded_at IS NULL)', name: 'idx_users_email_discarded_at_null'
  end
end
```

**Comment by jarednorman** [comment]
I think Rails uniqueness validations should be skipped now, and as outlines above, the trick is to use a composite index that includes the `discarded_at` timestamp.

**Comment by jeffreycastro** [comment]
> @JamesDullaghan You can add an index to support the validation if you are using a nice database (PostgreSQL, MySQL...).
> 
> It would prevent undiscarding records though if there has been a conflicting record created, as @rsmithlal mentioned.
> 
> To insulate yourself from the potential craziness, you may want to have two unique indexes, ensuring you only ever have one discarded and one not discarded. It will depend on how you intend to use the data.
> 
> ```
> class AddUniquenessConstraint < ActiveRecord::Migration[5.2]
>   def change
>     add_index :users, %i[email], where: '(discarded_at IS NOT NULL)', name: 'idx_users_email_discarded_at_not_null'
>     add_index :users, %i[email], where: '(discarded_at IS NULL)', name: 'idx_users_email_discarded_at_null'
>   end
> end
> ```

shouldn't there be a `unique: true` on the second index?
