### ISSUE TITLE
add #discard!

### ISSUE THREAD

**Issue by frankhock** [jhawthorn/discard#4]
what are your thoughts on adding a bang discard method `discard!` which can throw a `Discard::Model::RecordNotDiscarded` error?

**Comment by jhawthorn** [comment]
Sounds great!

**Comment by rlue** [comment]
I'm curious: under what conditions might you expect `#discard` to fail (other than, say, running out of database connections or some kind of network failure between app/DB servers)?

**Comment by goravbhootra** [comment]
@rlue calling `discard` on a non-existent id. bang method definitely has its use cases.

**Comment by artemf** [comment]
@rlue Actually, even simple validation error can break the deletion, which is odd to say the least. I've looked at the code and it does simple `#save` to "soft-delete" the record, meaning a) validation error can break soft-deletion, b) any update callbacks can break (stop) soft-deletion, c) else?

The author seem to have a very particular idea about how to implement soft-deletion (which he calls "done right"), but validations breaking the deletion (or running update callbacks) seems very wrong to me.

**Comment by rlue** [comment]
@artemf that's an interesting point. What do you think the correct behavior should be? Bypass validation on discard (_e.g.,_ via `#update_columns`) and validate on restore?

**Comment by skatkov** [comment]
@artemf  I've been looking at paranoia gem before and wrote my own implementation that is very similar to discard approach. I never had a real world scenario, then I had to update data and discard a record at the same time (so i never ran into issue your mentioning).

While I agree with you notion. Have you experienced issues with behavior you mention here?
