### ISSUE TITLE
This gem doesn't do much

### ISSUE THREAD

**Issue by toobulkeh** [jhawthorn/discard#40]
Moving from paranoia, I find this gem difficult to swallow. All it appears to do is provide a naming convention around a discarded_at timestamp and a few small helpers.

The readme doesn't even mention that you have to replace a lot of references throughout your app to get the "soft delete" type behavior you'd expect (migrating from Paranoia or ActsAsParanoid).

For example, even a simple `Post.find` needs to be replaced with `Post.kept.find`.

I get that this approach is useful for a few reasons, like providing verbosity and explicitness throughout a Rails application (which is arguably against their values), or not doing anything magical or by mistake
but it doesn't seem like it has anything to do with soft-deletion, besides the naming convention.

Am I using this wrong or misunderstanding something?

**Comment by pjg** [comment]
I don't think you're missing anything. That's the whole idea of this gem. You want the swiss knife, go with paranoia :)

**Comment by skatkov** [comment]
Probably this simplicity is the biggest feature in my book. 
- It provides convenient API that I can re-use. 
- It seems that there is not much to maintain here... Major rails bump would not be an issue for this gem. 

This paragraph should hint why `Post.find` is not in a scope of this gem.
https://github.com/jhawthorn/discard#why-not-paranoia-or-acts_as_paranoid
