### ISSUE TITLE
discard has_and_belongs_to_many association

### ISSUE THREAD

**Issue by kashifnaseer** [jhawthorn/discard#64]
What is the best way to soft delete **has_and_belongs_to_many** associations as there is no rails model exists for has_and_belongs_to_many association?

lets say there are 2 models

      class Participant < ApplicationRecord
        has_and_belongs_to_many :company_employees
       end
  
      class CompanyEmployee < ApplicationRecord
        has_and_belongs_to_many :participants
      end

> This will create company_employees_participants middle/join table in database BUT without any model in Ruby on Rails. Where i can make settings for discard gem ? 

any idea how i can solve this requirement where we need to have soft delete in joined tables using has_and_belongs_to_many

**Comment by jarednorman** [comment]
`has_and_belongs_to_many` is generally inflexible and I don't know of a way to accomplish this. Because of the limitations of habtm associations, it's often prudent to default to creating the join model and using a "has_many through" associations to avoid problems like this.
