### ISSUE TITLE
All new records are discarded use-case

### ISSUE THREAD

**Issue by skatkov** [jhawthorn/discard#75]
I know that gem is feature-complete, but there is one possible use-case in the gem that I ran into -- and wanted to bring it up. 

I had a need to have all new recorders created discarded. It's really easy to do actually:

```ruby
class CreatePosts < ActiveRecord::Migration[5.0]
  def change
    create_table :posts do |t|
      t.datetime :discarded_at, default: -> { 'CURRENT_TIMESTAMP' }
    end
  end 
end
```

But I didn't find any way to actually overwrite this default.

```Ruby
Post.create(discarded_at: false)
Post.create(discarded_at:nil)
```

all these methods lead to the object being discarded in the end. It feels like there is some other obvious way that I'm missing here. 

Maybe someone has idea?

**Comment by skatkov** [comment]
So far, this is a solution I've landed with:
```
class Post < ApplicationRecord
  after_initialize  do |flow|
    flow.discarded_at = Time.now unless id
  end
end
```

**Comment by jarednorman** [comment]
The issue in behaviour you encountered is ActiveRecord behaviour and has nothing specifically to do with discard, so I'm closing this issue. That said, your solution is probably fine. Consider using `persisted?` rather than checking the ID, I assume that's semantically what you are going for there.
