### ISSUE TITLE
Support for Rails 7.0.0

### ISSUE THREAD

**Issue by dwightwatson** [jhawthorn/discard#80]
**Describe the bug**
Rails 7 has recently shipped and it looks like `discard` cannot be installed currently alongside it.

```
Bundler could not find compatible versions for gem "activerecord":
  In Gemfile:
    discard (>= 1.1) was resolved to 1.2.0, which depends on
      activerecord (>= 4.2, < 7)

    rails (~> 7.0.0) was resolved to 7.0.0, which depends on
      activerecord (= 7.0.0)
```

**To Reproduce**
Create a new rails 7.x app, add `discard` to the `Gemfile` and attempt to bundle.

You'll get the same error as above, where `discard` won't install alongside `activerecord` 7.

**Expected behavior**
The gem should be installable and work as intended on Rails 7.

**Additional context**
Rails 7.0.0, Ruby 3.0.3.

**Comment by jarednorman** [comment]
Not sure why you mention activejob-uniqueness.

Master supports Rails 7 if you need it urgently. I will cut a new gem when I get the chance.

**Comment by jarednorman** [comment]
I've cut v1.2.1 with support for ActiveRecord 7.
