### ISSUE TITLE
Nil when finding has_one association

### ISSUE THREAD

**Issue by lucydoja** [jhawthorn/discard#87]
**Describe the bug**
Hey there! I was implementing your `after_undiscard do` when I came up with an unexpected error/bug. I have a has_one association with a model called Address. I used `address.discard` on the `after_discard` which worked perfectly. However, when I tried the same for the undiscard the address is returning as nil (it does not find the address even if it is in the discarded list). I am using `address.with_discarded.discarded.undiscard_all` since I am in using the default scope. But even looking for `address` inside the callback returns nil so the following scopes are not the issue.

**To Reproduce**
1. Add Discard to a model with a has_one association
2. Discard the model alongside the association
3. Try to undiscard using the association

**Expected behavior**
It should find the association and undiscard it. 

**Additional context**
```
gem "rails", "~> 6.1.4"
ruby "3.1.2"
gem "discard", "~> 1.2"
```

**Comment by jhawthorn** [comment]
If it's a `has_one` you can't apply scopes like that. You'll have to unscope the association or do something similar... One of the reasons the default scope is undesirable 😅 

This is not an issue with the library.

**Comment by lucydoja** [comment]
Ok, I get it! I ended up using `Address&.with_discarded&.discarded&.where(employee_id: id)&.undiscard_all` and it is working perfectly for me (just in case someone needs an answer. Thank you!
