### ISSUE TITLE
Sequel Support

### ISSUE THREAD

**Issue by IsmailM** [jhawthorn/discard#90]
Hi,

Discard looks great!

I was wondering if there were any plans to add Sequel support.

Based on a super quick look at the codebase - there does not seem to be much ActiveRecord-specific code.

**Comment by jarednorman** [comment]
This project is generally considered to be feature complete. I am not interested in adding support for other database adapters, **but** if you create a gem that provides soft-deletion support in the same style as Discard, but for Sequel, I would love to link to it from the project's README. Thanks!
