### ISSUE TITLE
guard on discard

### ISSUE THREAD

**Issue by gioggi** [jhawthorn/discard#93]
Why not add a guard on discard method, like in aasm_state the option: guard. Guard option accept a method or a block. If can discard do the discard, unless raise an error. I don't know if there is now a feature like this, if there is please explain me it. Thank you ! :)

**Comment by jarednorman** [comment]
Thanks for the suggestion. You can simulate this kind of behaviour yourself without built-in support for it by writing a custom method or overriding a discard method.
