### ISSUE TITLE
`self.class.discard_column` as a boolean `is_discarded` for "if" and use `updated_at` for "when"

### ISSUE THREAD

**Issue by chiperific** [jhawthorn/discard#94]
I gotta believe you already have heard/thought of this strategy and made a choice, but I couldn't find it, so I'm asking.

We use `timestamps` on all our models, as Rails convention expects.

Our Data Architect couldn't understand why we wouldn't just use a boolean `is_discarded` field and `updated_at` field to achieve the same result. From their perspective, a constrained "true/false" is easier to index and query than a "NULL/NOT NULL" especially when the NOT NULL values are timestamps.

Did Discard ever consider just a boolean `is_discarded` field paired with using the `updated_at` column approach? And if so, what took it out of consideration?

**Comment by jarednorman** [comment]
I'm not sure that was ever seriously considered. Discard was designed to offer a fairly backwards-compatible experience for apps using [Paranoia](https://github.com/rubysherpas/paranoia). Discard was originally developed for use in [Solidus](https://github.com/solidusio/solidus) and maintaining the same schema as Paranoia made that change much smoother.

Using a boolean column has a major downside; it breaks a common use-case involving uniqueness constraints. Let's say you're implementing a blog and you want the slugs for the blog posts to be unique _among non-deleted posts_. You can do this with a composite contraint that includes the `discarded_at` timestamp column and the `slug` column. All discarded posts will (almost certainly) have unique timestamps, so you can have as many records with the same slug if they are soft-deleted, but only have one where that timestamp is null.

It's also useful to know when a post was discarded in systems where the soft-deleted posts can still be interacted with in some ways.
