### ISSUE TITLE
.discarded query

### ISSUE THREAD

**Issue by no1-knows** [jhawthorn/discard#98]
Hello, I'm not sure this is bug or not.
Even a little information would be helpful.

**Describe the bug**

```
User.discarded
=> SELECT [users].* FROM [users] WHERE [users].[discarded_at] IS NULL AND [users].[discarded_at] IS NOT 
```
Actual log is below. unscoped one is fine!

```
irb(main):001> User.discarded
/usr/local/bundle/gems/activerecord-sqlserver-adapter-7.0.4.0/lib/active_record/connection_adapters/sqlserver_adapter.rb:111: warning: undefining the allocator of T_DATA class TinyTds::Result
  SQL (1.0ms)  USE [webapp_development]
  User Load (2.9ms)  SELECT [users].* FROM [users] WHERE [users].[discarded_at] IS NULL AND [users].[discarded_at] IS NOT NULL

irb(main):002> User.unscoped.discarded
  User Load (19.9ms)  SELECT [users].* FROM [users] WHERE [users].[discarded_at] IS NOT NULL

```

```
class User < ApplicationRecord
  include Discard::Model
  default_scope -> { kept }

  def active_for_authentication?
    super && !discarded?
  end

  def inactive_message
    discarded? ? :discarded : super
  end
etc...
```

**Additional context**

discard (1.3.0)
ruby 3.2.2 (2023-03-30 revision e51014f9c0) [aarch64-linux]
Rails 7.0.8

**Comment by jarednorman** [comment]
Certainly a bug, as querying for records where a field both is and isn't null will never return results outside of some kind of Schrödinger's cat scenario, but not likely a bug in discard as it doesn't change the default scope. My guess this is caused by something in your application or dependencies, but I've no more insight than that.

**Comment by no1-knows** [comment]
I deleted `default_scope -> { kept }` at User model and works perfect!!!
Thank you for your support!

```
irb(main):004> User.discarded
  User Load (3.5ms)  SELECT [users].* FROM [users] WHERE [users].[discarded_at] IS NOT NULL
```
